avathar_bbpoints_controller:
  path: /bbpoints
  defaults: { _controller: 'avathar.bbpoints.controller:handle_ultimatepoints' }
avathar_bbpoints_list_controller:
  path: /bbpointslist
  defaults: { _controller: 'avathar.bbpoints.list.controller:handle_ultimatepoints_list' }
