parameters:
  avathar.bbpoints.table.points.bank: '%core.table_prefix%points_bank'
  avathar.bbpoints.table.points.config: '%core.table_prefix%points_config'
  avathar.bbpoints.table.points.log: '%core.table_prefix%points_log'
  avathar.bbpoints.table.points.lottery.history: '%core.table_prefix%points_lottery_history'
  avathar.bbpoints.table.points.lottery.tickets: '%core.table_prefix%points_lottery_tickets'
  avathar.bbpoints.table.points.values: '%core.table_prefix%points_values'